version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_vendora
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
