version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_vendora
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    hostname: vendora-minio
    container_name: vendora-minio
    restart: always
    depends_on:
      - postgres
    command: server --console-address :9001 /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Y2rbs7yRaN9qNKcv8VuX7CP3VZz8rF5YmmWYqx35bG6dHsM8QU
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
