definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.ActiveStatus:
    enum:
    - DR
    - SUS
    - AC
    type: string
    x-enum-varnames:
    - Draft
    - Suspend
    - Activate
  models.AuthInput:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  models.ProductEntity:
    properties:
      active:
        allOf:
        - $ref: '#/definitions/models.ActiveStatus'
        description: Active is change from Admin
      category_id:
        description: CategoryID
        type: integer
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      desc:
        description: Description
        type: string
      discount_price:
        description: DiscountPrice
        type: number
      id:
        type: integer
      images:
        description: Images
        items:
          type: string
        type: array
      price:
        description: Price is total price
        type: number
      rating:
        description: Rating
        type: integer
      short_desc:
        description: ShortDescription
        type: string
      sku:
        description: SKU is Stock keeping unit
        type: string
      slug:
        description: Slug
        type: string
      stock:
        description: Stock
        type: integer
      tags:
        description: Tags
        items:
          type: string
        type: array
      title:
        description: Title
        type: string
      updatedAt:
        type: string
      user_id:
        description: UserID
        type: integer
    type: object
  models.ProductInput:
    properties:
      category_id:
        type: integer
      description:
        type: string
      discount_price:
        type: number
      images:
        items:
          type: string
        type: array
      price:
        type: number
      short_desc:
        type: string
      sku:
        type: string
      stock:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  models.TagsInput:
    properties:
      tags:
        items:
          type: string
        type: array
    type: object
  models.TokenBundlerOutput:
    properties:
      expire:
        description: Expire is time for expire token
        type: string
      refresh:
        description: Refresh is string that for refresh old token
        type: string
      token:
        description: Token is string that hashed by paseto
        type: string
    type: object
  models.UserEntity:
    properties:
      balance:
        description: Balance
        type: number
      first_name:
        description: FirstName
        type: string
      last_name:
        description: LastName
        type: string
      mobile:
        description: Mobile phone number of account owner
        type: string
      products:
        description: Products just not null for seller
        items:
          $ref: '#/definitions/models.ProductEntity'
        type: array
      roles:
        description: Roles contains account access level permissions
        items:
          type: string
        type: array
      suspended:
        description: Suspended uses as determination flag for account suspension situation
        type: boolean
      user_name:
        description: UserName
        type: string
    type: object
  vendora.BaseResult:
    properties:
      errors:
        description: Errors provides list off error that occurred in processing request
        items:
          type: string
        type: array
      result:
        description: Result single/array of any type (object/number/string/boolean)
          that returns as response
      result_count:
        description: ResultCount specified number of records that returned in result_count
          field expected result been array.
        type: integer
    type: object
info:
  contact: {}
paths:
  /{id}:
    delete:
      consumes:
      - application/json
      description: delete a product with specific ID
      parameters:
      - description: product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: always return status 200 but body contains error
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  type: integer
              type: object
      security:
      - session: []
      summary: delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      parameters:
      - description: product ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: always returns status 200 but body contains error
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  $ref: '#/definitions/models.ProductEntity'
              type: object
      summary: GetProduct with specific ID
      tags:
      - products
  /add:
    post:
      consumes:
      - application/json
      description: Add new production with specific User
      parameters:
      - description: Product Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.ProductInput'
      responses:
        "200":
          description: always returns status 200 but body contains error
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  $ref: '#/definitions/models.ProductEntity'
              type: object
      security:
      - session: []
      summary: Add New Product
      tags:
      - products
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: get user information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  $ref: '#/definitions/models.UserEntity'
              type: object
      summary: user info
      tags:
      - user
  /api/v1/user/{role}:
    get:
      consumes:
      - application/json
      description: get all user for admin
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/models.UserEntity'
                  type: array
              type: object
      security:
      - session: []
      summary: get all user
      tags:
      - user
  /api/v1/user/EditUser:
    patch:
      consumes:
      - application/json
      description: edit user with specific ID
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  $ref: '#/definitions/models.UserEntity'
              type: object
      summary: edit user
      tags:
      - user
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: log in with specific user name
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  $ref: '#/definitions/models.TokenBundlerOutput'
              type: object
      summary: log in
      tags:
      - user
  /api/v1/user/signup:
    post:
      consumes:
      - application/json
      description: Create New user
      parameters:
      - description: AuthInput
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.AuthInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  $ref: '#/definitions/models.TokenBundlerOutput'
              type: object
      summary: Create New user
      tags:
      - user
  /edit/{id}:
    patch:
      consumes:
      - application/json
      description: edit a product with specific ID
      parameters:
      - description: product input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.ProductInput'
      produces:
      - application/json
      responses:
        "200":
          description: always return status 200 but body contains error
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  $ref: '#/definitions/models.ProductEntity'
              type: object
      security:
      - session: []
      summary: edit a product
      tags:
      - products
  /mio/download/{token}:
    get:
      consumes:
      - application/octet-stream
      description: upload specified file to mio service with specified properties
      parameters:
      - description: access token of file
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: always returns status 200 but body contains errors
          schema:
            $ref: '#/definitions/vendora.BaseResult'
      security:
      - Authenticate Header: []
      summary: uploading file to mio service
      tags:
      - mio
  /mio/image/{size}/{token}:
    get:
      consumes:
      - application/octet-stream
      description: upload specified file to mio service with specified properties
      parameters:
      - description: width of requested image
        in: path
        name: size
        required: true
        type: integer
      - description: access token of file
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: always returns status 200 but body contains errors
          schema:
            $ref: '#/definitions/vendora.BaseResult'
      security:
      - Authenticate Header: []
      summary: uploading file to mio service
      tags:
      - mio
  /mio/upload/{tag}:
    post:
      consumes:
      - multipart/form-data
      description: uploading specified file to mio service with specified properties
      parameters:
      - description: uploading file
        in: formData
        name: file
        required: true
        type: file
      - description: string enums
        enum:
        - public
        - private
        - chat
        - profile
        in: path
        name: tag
        required: true
        type: string
      - description: 'authentication paseto token [Required If AuthMode: paseto]'
        in: header
        name: Authenticate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: always returns status 200 but body contains errors
          schema:
            $ref: '#/definitions/vendora.BaseResult'
      security:
      - Authenticate Header: []
      - Session: []
      summary: uploading file to mio service
      tags:
      - mio
  /tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: slice of tags
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.TagsInput'
      produces:
      - application/json
      responses:
        "200":
          description: always return status 200 but body contains error
          schema:
            allOf:
            - $ref: '#/definitions/vendora.BaseResult'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/models.ProductEntity'
                  type: array
              type: object
      summary: get products with same tags
      tags:
      - products
swagger: "2.0"
